name: Deploy Memory Card Game

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install deps and build
        run: |
          npm ci
          npm run build

      - name: Upload to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: rene
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/renem.me/memory-card-game"
