name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]  # or 'master' depending on your repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Connect and deploy to Droplet
      uses: appleboy/ssh-action@master
      with:
        host: 167.99.222.76
        username: rene
        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          cd /var/www/renem.me/memory-card-game
          git pull origin main
          npm install
          npm run build
